# Time interval of data
Time interval:
  Start_year: 2015
  Start_month: 1
  End_year: 2025
  End_month: 12        

# Name
TOKENS: "NASDAQ:GOOG,NASDAQ:AVGO,NYSE:LLY,NYSE:GS,NYSE:AXP,NYSE:MRK,NASDAQ:ISRG,NASDAQ:MU,NASDAQ:STX"

# Time frequency of the data 'minute', 'hour', 'day'
Frequency: day

